== Elasticity

// tag::quoute[] 
The manager stays responsive under varying workloads.
// end::quoute[] 

_Reactive manager_ can react to changes in the tasks input rate by increasing or decreasing resources available for the process. 
This implies designs of processes that have no contention points or central bottlenecks, resulting in the ability to share the tasks with peers and distribute inputs among them. 
Processes built by the reactive manager are predictive and easy to live performance check.

TIP: You are never too busy if you are running an efficient operation.

_Elasticity_ is achieved by redundancy in resources sharing.

=== Implications

_Elasticity_ in a face of resource sharing is limited by actor characteristics. Human beings are not scalable and rarely interchangeable.

Common mental model for operations processing is orchestration. In such model manager is the central point in the process flow (linked actions). Each individual action is observed by a manager. Action effects are consumed by a manager and used for further state computation (decision making).
The process flow is anemic. 

[#Navigate]
<- link:reactive_principles.adoc[Back to Reactive Principles]
