== Responsiveness

The manager should respond on time. + 
Always.

It doesn't matter if a manager has all the resources needed to run the processes right if a manager cannot react/respond within the time constraints. 
It is not only about the fast response time, but also about managing changes. 

The _Reactive Manager_ effectively detects and deals with problems. Focus on providing rapid and consistent response times. In the worst-case, a manager does not know the right answer or provide not a complete answer, but still, delivers value.

=== Implications

The manager is always a proxy in the data flow. The manager is either asked for some information or given the information.

The entry point for the _Responsiveness_ is managers' input channels. Nowadays, we are overwhelmed with possible inputs: social media, phone, text messages, emails, notifications, face-to-face, group meetings, etc. All possible kinds of consumable information. There are some general suggestions for response times.

*Face-to-Face*::
JIT. Just-In-Time. A question needs to be answered during the conversation. If there is not enough information to provide a complete (or correct) response: the partial response is given. With the agreement on When/How further information can be received.

*Emails*::
Hours to Days. Hard to imagine the setup without 'a corporate mail box'. The main source of truth for escalations and decisions approvals. _One-size-fits-all_ approach turns *emails* into the noisiest channel. Hughe distribution lists; partial context or no context; blurred timelines; not clear, not defined priorities. All of these require extra care to provide a consistent response. 

////
write about mental model to cope with input channels.

////

Same expectations and same understanding of communication channel should be shared between all the counter parties. 

[#Back_To]
<- link:reactive_principles.adoc[Back to Reactive Principles]
